spring:
  application:
    name: pos
  datasource:
    url: jdbc:postgresql://178.128.57.132:3242/fastapi
    username: springdb
    password: ITE2@2024
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
file_storage:
  image_location: "/filestorage/images/"
  client_path: "/images/**"



springdoc:
  swagger-ui:
    path: /api

